### ISSUE TITLE
carma-msg foxy/devel didn't match carma-web-ui foxy/devel branch 

### ISSUE THREAD

**Issue by cshang412** [usdot-fhwa-stol/carma-web-ui#128]
**Description:**

In global_variables.js there are so many cav_msg being used, but the cav_msg only has ros1 (catkin) version, my system only has ros2-foxy installed, each time i launch  websocket(ros2), there are lots of errors report from the socker client like this:
`ros2 run rosbridge_server rosbridge_websocket
registered capabilities (classes):
 - <class 'rosbridge_library.capabilities.call_service.CallService'>
 - <class 'rosbridge_library.capabilities.advertise.Advertise'>
 - <class 'rosbridge_library.capabilities.publish.Publish'>
 - <class 'rosbridge_library.capabilities.subscribe.Subscribe'>
 - <class 'rosbridge_library.capabilities.defragmentation.Defragment'>
 - <class 'rosbridge_library.capabilities.advertise_service.AdvertiseService'>
 - <class 'rosbridge_library.capabilities.service_response.ServiceResponse'>
 - <class 'rosbridge_library.capabilities.unadvertise_service.UnadvertiseService'>
[INFO] [1639147561.491522891] [rosbridge_websocket]: Rosbridge WebSocket server started on port 9090

[INFO] [1639147829.862033795] [rosbridge_websocket]: Client connected. 1 clients total.
[INFO] [1639147829.887134582] [rosbridge_websocket]: [Client 0] Subscribed to /environment/intersection_signal_group_ids
[ERROR] [1639147830.471864559] [rosbridge_websocket]: [Client 0] [id: subscribe:/system_alert:2] subscribe: Unable to import cav_msgs.msg from package cav_msgs. Caused by: No module named 'cav_msgs'
[ERROR] [1639147830.906928806] [rosbridge_websocket]: [Client 0] [id: subscribe:/system_alert:3] subscribe: Unable to import cav_msgs.msg from package cav_msgs. Caused by: No module named 'cav_msgs'`

**How i use carma-web-ui:**

i use carma-web-ui foxy/devel branch and carma-msg foxy/deve/ branch, the launch the rosbridge_websocket.launch with defult config, then i publish an systemAlert topic manually, then i got error upon. 

**Expect behavior:**

carma-msg and carma-web-ui in foxy/devel branch can match properly

**Comment by msmcconnell** [comment]
@cshang412 foxy/develop is still under heavy development and should not be considered stable. It should become stable within the next month. 

As far as your current issue goes, cav_msgs is a ROS1 only package and will not work in ROS2. The messages in cav_msgs have been split into multiple use case specific packages for ROS2 called carma_*_msgs (such as carma_localization_msgs etc.) ROS2 packages need to use these message sets instead of cav_msgs.

**Comment by msmcconnell** [comment]
All the ros2 stuff is aligned on develop as of 4.0 release
